import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { CssBaseline } from "@mui/material";
import { OriginalTheme } from "@/style/muiTheme/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "権藤大樹 Official Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        {/* nextjsとMUIを共存 */}
        <AppRouterCacheProvider>
          {/* MUIのResetCSS */}
          <CssBaseline />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
